### PR TITLE
Delete history items off the list

### LINKED ISSUE #36: any way to delete entries from this list?
any way to delete entries from this list? when you push ctrl+R?

### PR DESCRIPTION
**Pull request by p1r473**
Delete history items off the list
Just select a line you want to delete and click the delete key on your keyboard
Fixes #36 

This actually took me an entire day to figure out how to do, even though its just a few lines.
I'd welcome any better way. I did try to leverage zsh-hist but just couldn't get it to work. I tried everything here too: https://unix.stackexchange.com/a/605328 including the dc() function. If you can find a way I'd love to see it

I merged https://github.com/joshskidmore/zsh-fzf-history-search/pull/32 while I was in there

### CODE REVIEW

**Comment by p1r473** [comment]
I merged #32 while I was in there

**Comment by p1r473** [comment]
@joshskidmore can you give this a test and see if it works for you?

**Comment by joshskidmore** [comment]
I apologize, I've been away from the computer travelling for work.

I believe this might be better served as a new zsh plugin (which it appears you've done). There are a lot of caveats with deleting history - such as handling the zsh reload, reloading screen or tmux to recognize the changes, and preventing history corruption. This plugin was intended as a read-only, quick historical reference with timestamps.

**Comment by p1r473** [comment]
@joshskidmore Its been having the issue where after i view the history, delete a line, then select a line, the wrong line is selected.
I think the deletion happens in a subshell so the selection acts as if the deletion never happened
I've been banging my head on this for hours. ChatGPT, CoPilot, and Gemini couldnt figure it out either.

I was hoping maybe you could take a look?

https://raw.githubusercontent.com/p1r473/zsh-hist-delete-fzf/refs/heads/main/zsh-hist-delete-fzf.plugin.zsh

**Pull request closed without merging**
